"""string2text

迁移 ID: 1a9f061420dc
父迁移: 8e0e82953dde
创建时间: 2025-08-06 12:26:57.631827

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "1a9f061420dc"
down_revision: str | Sequence[str] | None = "8e0e82953dde"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic and JohnRichard4096 - please adjust! ###
    op.drop_table("_alembic_tmp_suggarchat_group_config", if_exists=True)
    with op.batch_alter_table("fishing_user_meta", schema=None) as batch_op:
        batch_op.alter_column(
            "progress",
            existing_type=sa.VARCHAR(length=1024),
            type_=sa.TEXT(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fishing_user_meta", schema=None) as batch_op:
        batch_op.alter_column(
            "progress",
            existing_type=sa.TEXT(),
            type_=sa.VARCHAR(length=1024),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
