"""add_blacklist

迁移 ID: 21e12f10c0fd
父迁移: abaa39427c6d
创建时间: 2025-07-10 10:22:17.690373

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "21e12f10c0fd"
down_revision: str | Sequence[str] | None = "abaa39427c6d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "group_blacklist",
        sa.Column("group_id", sa.String(length=50), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("group_id", name=op.f("pk_group_blacklist")),
        info={"bind_key": ""},
    )
    op.create_table(
        "private_blacklist",
        sa.Column("user_id", sa.String(length=50), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_private_blacklist")),
        info={"bind_key": ""},
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("private_blacklist")
    op.drop_table("group_blacklist")
    # ### end Alembic commands ###
