"""fix_db

迁移 ID: 248bbf01ddfd
父迁移: 2fb137c0857a
创建时间: 2025-08-06 11:56:58.595765

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

revision: str = "248bbf01ddfd"
down_revision: str | Sequence[str] | None = "2fb137c0857a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fishing_user_meta", schema=None) as batch_op:
        batch_op.add_column(sa.Column("progress", sa.JSON(), nullable=False))
        batch_op.drop_column("has_fish")

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fishing_user_meta", schema=None) as batch_op:
        batch_op.add_column(sa.Column("has_fish", sqlite.JSON(), nullable=False))
        batch_op.drop_column("progress")

    # ### end Alembic commands ###
