"""extend_player_meta

迁移 ID: 2582cfe00a88
父迁移: 2e711ddbe4c7
创建时间: 2025-08-01 12:41:40.845107

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2582cfe00a88"
down_revision: str | Sequence[str] | None = "2e711ddbe4c7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fishing_user_meta", schema=None) as batch_op:
        batch_op.add_column(sa.Column("lucky_of_the_sea", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("multi_fish", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("feeding", sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fishing_user_meta", schema=None) as batch_op:
        batch_op.drop_column("feeding")
        batch_op.drop_column("multi_fish")
        batch_op.drop_column("lucky_of_the_sea")

    # ### end Alembic commands ###
