"""user_data

迁移 ID: 2991fd9f715e
父迁移: 21e12f10c0fd
创建时间: 2025-07-12 20:24:14.353782

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '2991fd9f715e'
down_revision: str | Sequence[str] | None = '21e12f10c0fd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suggar_user_data',
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('last_daily', sa.FLOAT(), nullable=False),
    sa.Column('daily_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_suggar_user_data')),
    info={'bind_key': ''}
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suggar_user_data')
    # ### end Alembic commands ###
