"""fishing_prompt

迁移 ID: 2e711ddbe4c7
父迁移: b509501ca994
创建时间: 2025-07-31 11:34:19.553284

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2e711ddbe4c7"
down_revision: str | Sequence[str] | None = "b509501ca994"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fish_meta", schema=None) as batch_op:
        batch_op.add_column(sa.Column("prompt", sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fish_meta", schema=None) as batch_op:
        batch_op.drop_column("prompt")

    # ### end Alembic commands ###
