"""add_fising_progress

迁移 ID: 2fb137c0857a
父迁移: 9e9f70cb87ef
创建时间: 2025-08-06 11:30:05.368462

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '2fb137c0857a'
down_revision: str | Sequence[str] | None = '9e9f70cb87ef'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fishing_user_meta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_fish', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fishing_user_meta', schema=None) as batch_op:
        batch_op.drop_column('has_fish')

    # ### end Alembic commands ###
