"""str_len

迁移 ID: 6b59df13df3b
父迁移: 6566a1745877
创建时间: 2025-07-14 11:52:42.696909

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "6b59df13df3b"
down_revision: str | Sequence[str] | None = "6566a1745877"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("suggar_user_data", schema=None) as batch_op:
        batch_op.alter_column(
            "user_id",
            existing_type=sa.VARCHAR(length=50),
            type_=sa.String(length=255),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("suggar_user_data", schema=None) as batch_op:
        batch_op.alter_column(
            "user_id",
            existing_type=sa.String(length=255),
            type_=sa.VARCHAR(length=50),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
