"""add_insights

迁移 ID: 82a432ac66ce
父迁移: 2582cfe00a88
创建时间: 2025-08-01 14:10:03.681883

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "82a432ac66ce"
down_revision: str | Sequence[str] | None = "2582cfe00a88"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fishing_user_meta", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("last_fishing_time", sa.DateTime(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("today_fishing_count", sa.Integer(), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fishing_user_meta", schema=None) as batch_op:
        batch_op.drop_column("today_fishing_count")
        batch_op.drop_column("last_fishing_time")

    # ### end Alembic commands ###
