"""fix_db

迁移 ID: 8e0e82953dde
父迁移: 248bbf01ddfd
创建时间: 2025-08-06 12:02:01.853542

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

revision: str = "8e0e82953dde"
down_revision: str | Sequence[str] | None = "248bbf01ddfd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fishing_user_meta", schema=None) as batch_op:
        batch_op.alter_column(
            "progress",
            existing_type=sqlite.JSON(),
            type_=sa.String(length=1024),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fishing_user_meta", schema=None) as batch_op:
        batch_op.alter_column(
            "progress",
            existing_type=sa.String(length=1024),
            type_=sqlite.JSON(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
