"""extend_player_meta

迁移 ID: 955a0e8e0d6d
父迁移: a33cc4604d6d
创建时间: 2025-08-01 11:03:47.023027

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "955a0e8e0d6d"
down_revision: str | Sequence[str] | None = "a33cc4604d6d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fishing_user_meta", schema=None) as batch_op:
        batch_op.add_column(sa.Column("multi_fish", sa.Integer(), nullable=False))
        batch_op.drop_column("fast_fishing")

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fishing_user_meta", schema=None) as batch_op:
        batch_op.add_column(sa.Column("fast_fishing", sa.INTEGER(), nullable=False))
        batch_op.drop_column("multi_fish")

    # ### end Alembic commands ###
