"""add_switch

迁移 ID: 9e9f70cb87ef
父迁移: 82a432ac66ce
创建时间: 2025-08-04 22:58:18.417252

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '9e9f70cb87ef'
down_revision: str | Sequence[str] | None = '82a432ac66ce'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suggar_function_switch',
    sa.Column('group_id', sa.String(length=255), nullable=False),
    sa.Column('fishing_enabled', sa.Boolean(), nullable=False),
    sa.Column('daily_enabled', sa.Boolean(), nullable=False),
    sa.Column('luck_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('group_id', name=op.f('pk_suggar_function_switch')),
    info={'bind_key': ''}
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suggar_function_switch')
    # ### end Alembic commands ###
