"""Init

迁移 ID: cf061fbe3bba
父迁移: 53691b7cf82d
创建时间: 2025-07-24 18:06:32.747728

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "cf061fbe3bba"
down_revision: str | Sequence[str] | None = "53691b7cf82d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "group_blacklist",
        sa.Column("group_id", sa.String(length=50), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("group_id", name=op.f("pk_group_blacklist")),
        info={"bind_key": ""},
    )
    op.create_table(
        "private_blacklist",
        sa.Column("user_id", sa.String(length=50), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_private_blacklist")),
        info={"bind_key": ""},
    )
    op.create_table(
        "suggar_user_data",
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("last_daily", sa.DateTime(), nullable=False),
        sa.Column("daily_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_suggar_user_data")),
        info={"bind_key": ""},
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("suggar_user_data")
    op.drop_table("private_blacklist")
    op.drop_table("group_blacklist")
    # ### end Alembic commands ###
