name: CI/CD Pipeline

on:
  push:
    branches:
      - "*"
  pull_request:
    branches-ignore:
      - "*"

jobs:
  runTest:
    name: Run Tests on Push
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache virtualenv
        uses: actions/cache@v4
        with:
          path: .venv
          key: ${{ runner.os }}-uv-${{ hashFiles('pyproject.toml', 'uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set environment
        run: |
          uv venv .venv
          uv sync

      - name: Install dependencies
        run: |
          pipx install nb-cli

      - name: Get Python path
        run: |
          PYTHON_BIN="$(uv run python -c 'import sys; print(sys.executable)')"
          echo "PYTHON_BIN=$PYTHON_BIN" >> $GITHUB_ENV

      - name: Run Pyright
        uses: jakebailey/pyright-action@v2
        with:
          python-path: ${{ env.PYTHON_BIN }}
          pylance-version: latest-release

      - name: Setup database
        run: |
          echo "Setting up database for CI..."
          uv run nb orm upgrade head

      - name: Load test
        run: |
          uv run run-test.py
